accounts:
  - name: alice
    coins: ["18500000cht", "100000cgas"]
  - name: bob
    coins: ["18500000cht", "100000cgas"]
  - name: carlos
    coins: ["5000000cht", "5000000cgas"]
    address: chronic1gqqhp8clrckg22d2dfn2z5rs85w3pynae7648x
validator:
  name: alice
  staked: "100000000cgas"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: [ "5cht", "100000cgas" ]
  coins_max: [ "10000cht", "10000cgas" ]
#host:
#  rpc: ":26659"
#  p2p: ":26658"
#  prof: ":6060"
#  grpc: ":9090"
#  api: ":1318"
genesis:
  chain_id: "chronic-grapes"
  app_state:
    staking:
      params:
        bond_denom: "cht"
    mint:
      params:
        mint_denom: "cgas"
    crisis:
      constant_fee:
        denom: "cgas"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "cgas"
