accounts:
  - name: alice
    coins: ["210000000tcht", "200000000cgas"]
  - name: bob
    coins: ["10000tcht", "100000000cgas"]
validator:
  name: alice
  staked: "1000000tcht"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: [ "5tcht", "100000cgas" ]
  coins_max: [ "10000tcht", "10000cgas" ]
build:
  proto:
    third_party_paths: ["third_party/proto"]
genesis:
  chain_id: "modified-grapes"
  app_state:
    staking:
      params:
        bond_denom: "tcht"
    mint:
      params:
        mint_denom: "cgas"
    crisis:
      constant_fee:
        denom: "cgas"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "cgas"
